# Please keep AllCops, Bundler, Style, Metrics groups and then order cops
# alphabetically
AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: false
Bundler/OrderedGems:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/RaiseArgs:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Metrics/LineLength:
  Enabled: false
