language: ruby
sudo: false
cache: bundler
install: true
env:
  global:
    - JRUBY_OPTS="--debug --dev"
script:
  - 'if [[ "$TRAVIS_RUBY_VERSION" =~ "jruby" ]]; then rvm get head && rvm reload && rvm use --install $TRAVIS_RUBY_VERSION && gem install bundler; fi'
  - 'bundle install'
  - './script/ci'
rvm:
  - 2.2.5
  - 2.3.1
  - jruby-9.1.2.0
  - jruby-head
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: jruby-9.1.2.0
